### ISSUE TITLE
Migrate release announcements

### ISSUE THREAD

**Issue by yanesca** [ARMmbed/mbedtls#3226]
## Background

Release announcements are currently sent to a list of emails originating from the [website](https://tls.mbed.org), but which faces several issues (we don't have a mechanism to extend it anymore and sending out the announcements has an unacceptable delay).

## Task Breakdown

- [x] create a child page for the release process in confluence for announcement emails and document the remaining subtasks there
- [x] ask @danh-arm about the process and create a new release mailing list (eg mbed-tls-announce@lists.trustedfirmware.org)
- [x] create an official email address for the purpose of sending the announcements from that (eg mbed-tls@trustedfirmware.org)
- [x] compose a last message to the old list with an announcement about the move and
 point them to the new announcement list and invite them to the developer lists as well. Have the text reviewed by @danh-arm or @yanesca 
- [x] send out the last message (on how to do that, see "release announcement" on the Release Process confluence page)
- [ ] draft an email template for a release email that is sent out 1 or 2 weeks prior the actual release
- [x] revise and improve the template for the second release email. (for a sample release email see "release announcement" on the Release Process confluence page)
- [x] have both of the templates reviewed by @danh-arm and @yanesca

**Comment by danh-arm** [comment]
This is linked to #3231 in that we want to announce that change at the same time.

**Comment by yanesca** [comment]
The release announcements have been going out on the new announcement list for more than 6 months now. Sending an advance announcement wasn't part of the process and not necessary for the new release process.

Closing this issue as completed.
