### ISSUE TITLE
Internal Threat Model

### ISSUE THREAD

**Issue by yanesca** [ARMmbed/mbedtls#3252]
## Story:

The Mbed TLS threat model has been always precedent based, and hasn't been precisely defined in writing. Mistakes and deliberate exceptions have been accumulated over the years and reached the point where both classifying vulnerabilities and managing expectations are extremely difficult. The goal of this task to produce a written reference about the security of the library, to help classifying vulnerabilities and to serve as a basis for a public threat model.

## Task breakdown:

- [ ] Develop and agree on the data flow diagram, boundary analysis, attacker and asset list
- [ ] Find and list high level threats
- [ ] Discuss and document mitigation strategy
- [ ] Validate the model

**Comment by yanesca** [comment]
Closing down in the favour of #3503, #3504, #3505, #3506, #3507, #3508.
