### ISSUE TITLE
Make the website static

### ISSUE THREAD

**Issue by yanesca** [ARMmbed/mbedtls#3256]
## Background:                                                                      
                                                                                
After removing the website from the release process, there won't be any need to update the Mbed TLS website. To minimise effort spent on maintenance we will make the website static.

## Task breakdown:                                                             
(Many of these steps will require raising a PR on the website repository.)

- [ ] Create an archive branch and a static branch from the current website                                                                           
- [ ] Dump and archive the database of the website, add it to the archive branch. Update readme on this branch and warn that the website database is in it as well and contains user data and credentials. This branch should never be published as it is.                                                                
- [ ] Capture a snapshot of the website (with eg. wget) and remove links/references 
  to dynamic parts (login, etc.)                                           
- [ ] Add links wherever necessary to the new location of releases and the wiki (PR 
  against the static branch)                                                    
- [ ] Assess the security of the resulting static website, including the            
  corresponding infrastructure, fix critical issues and start tracking the rest 
- [ ] Make the static website live

**Comment by yanesca** [comment]
This is a duplicate, closing in favour of https://github.com/ARMmbed/mbedtls/issues/4087.
