### ISSUE TITLE
TLS Cipher 2a: tickets: use PSA for protection

### ISSUE THREAD

**Issue by mpg** [ARMmbed/mbedtls#5203]
In `ssl_ticket.c`, use `psa_aead` instead of `mbedtls_cipher` in order to protect tickets when `MBEDTLS_USE_PSA_CRYPTO` is enabled.

- [x] In `struct mbedtls_ssl_ticket_key` replace* the cipher context with two fields with types `mbedtls_svc_key_id_t` and `psa_algorithm_t`, and adapt `mbedtls_ssl_ticket_free()` accordingly. 
- [x] In `ssl_ticket_gen_key()`, set appropriate attributes (will need to use the algorithm now stored in the context) and import the the random bytes with `psa_import_key()`. (Compared to using `psa_generate_key()`, this allows for better code sharing between PSA and non-PSA, and is also preferable if we even want to enable PSA builds without `ENTROPY_C`, see https://github.com/ARMmbed/mbedtls/issues/5156#issuecomment-984662340)
- [x] In `mbedtls_ssl_ticket_setup()`, translate the `cipher` to the appropriate algorithm using the utility function created in #5182  and store that in the context before calling `ssl_ticket_gen_key()` - the calls to `mbedtls_cipher_setup()` don't make sense with PSA and can be simply removed.
- [x] In `mbedtls_ssl_ticket_write()`, instead of `mbedtls_cipher_auth_encrypt_ext()` call `psa_aead_encrypt()`.
- [x] In `mbedtls_ssl_ticket_parse()`, instead of `mbedtls_cipher_auth_decrypt_ext()` call `psa_aead_decrypt()`.
- [x] NEW: also handle the `mbedtls_ssl_ticket_rotate()` than was added by #5501
 
*Note: this describes the final result; in terms of execution, it may be desirable to first add the new fields (keeping the existing ones), then modify the functions gradually, and finally remove the old fields when `MBEDTLS_USE_PSA_CRYPTO` is enabled.

Depends on: #5181 for tests, #5182 for translation function.

**Comment by mpg** [comment]
This task should wait until #5501 has been merged, so that the new call to `mbedtls_cipher_setkey()` that it introduces can be handled as well.

**Comment by mpg** [comment]
Removing "needs: preceding PR" as #5501 has been merged.
