### ISSUE TITLE
Code Size Comparison Script: decide expected feature/behavior

### ISSUE THREAD

**Issue by yanrayw** [ARMmbed/mbedtls#7912]
We have `code_size_compare.py` to measure code size but with limited features. This issue is to collect and decide expected features in code size measurement script.

**TODO:**
- [ ] Support to build with various compilers, like `gcc`, `clang`, `armclang`, `arm-none-eabi-gcc`.
- [ ] Support to build with various configurations, like `default`, `full`, `baremetal`.
- [ ] Should be able to modify `CFLAGS`.
- [ ] Should be able to build with various arm target.
- [x] Support to only list modified `OBJECTS`. (covered by #7937 )
- [x] Output in markdown format to easily show code size changes in Github comment. (covered by #7937 )
- [ ] Do we need more tools to track code size other than `size`? Like `nm`, `objdump`

**DoD:**
A list of requirements collected. We should split small PRs to add feature one by one.

**Comment by tom-cosgrove-arm** [comment]
Additional input: have a look at some of the things @daverodgman’s mtest script can do
